### ISSUE TITLE
upgrade.php MySQL-Strict error

### ISSUE THREAD

**Issue by BerndJM** [WBCE/Download-Gallery-WBCE#10]
Da sind  für MySQL-Strict noch Fehlerchen in der upgrade.php (war auch schon in der vorherigen Version drin):
Zeile 73:
Can't DROP 'extposition' ...
Zeile 72:
Duplicate column name 'position'...

Da sollte man wohl mal entsprechende Abfragen drum klöppeln.

**Comment by webbird** [comment]
Ist erledigt, wenn auch etwas "quick & dirty".
