### ISSUE TITLE
Drag & Drop not working with Argos Theme

### ISSUE THREAD

**Issue by webbird** [WBCE/Download-Gallery-WBCE#2]
http://forum.wbce.org/viewtopic.php?pid=3868#p3868

**Comment by webbird** [comment]
In Argos, an old - maybe stripped? - version of the jQuery UI is loaded, and there is no sortable plugin. So, there will be no drag&drop in Argos Theme for now.

**Comment by NorHei** [comment]
Whats whith this issue ?? Wontfix , Fixed , ... What hapened ?

**Comment by webbird** [comment]
I'm still waiting for some feedback. Drag & drop should work with marmot's fix.
