### ISSUE TITLE
Suche funktioniert mit WBCE nicht

### ISSUE THREAD

**Issue by instantflorian** [WBCE/Download-Gallery-WBCE#7]
https://forum.wbce.org/viewtopic.php?id=3245
- download_gallery_search muss in download_gallery_3_search geändert werden
- $tablename ist leer bzw. nicht definiert

Ich habe im Forum die entsprechenden Fixes gepostet, möglicherweise funktionieren diese dann aber nicht mit BC.

**Comment by webbird** [comment]
Hab den Fix übernommen. Funktioniert sicherlich auch mit BC.
